### ISSUE TITLE
Create base python project

### ISSUE THREAD

**Issue by natron2244** [clevertech/ml-stack-answers#1]
### Description
Establish where we keep the dataset in the project -- as a zip file or extracted
Check for dataset in python

**Comment by natron2244** [comment]
@fikander I think this issue can now be closed. Was there anything else you want to do in the init setup?

**Comment by chadfurman** [comment]
@natron2244 @fikander I agree, this issue should be closed.  I'm closing it, and we can re-open if we disagree.  

For now, we have a really nice initial setup thanks to @fikander using the cookie cutter template.
