### ISSUE TITLE
Parse the dataset

### ISSUE THREAD

**Issue by natron2244** [clevertech/ml-stack-answers#3]
### Description
As a developer I want to have the data from https://archive.org/download/stackexchange/serverfault.com.7z, load into python data structure so I can start working with my data in code.

Questions:
- Parameter/input for the application the serverfault URL/.7z?

**Comment by chadfurman** [comment]
How is this different from https://github.com/clevertech/ml-stack-answers/issues/4 ?

**Comment by chadfurman** [comment]
I am working on this by extending ml_stack_answers.cli.py to take a path to the folder containing all the files:

```
@click.option('--data', default='data/', help='Path to folder containing Badges.xml, Comments.xml, PostHistory.xml, PostLinks.xml, Posts.xml, Tags.xml, Users.xml, and Votes.xml (i.e. the extracted archive from StackOverflow)')
```

and then creating custom extractor classes for each file.  Each extractor class will be namespaced by the algorithm it is designed for.  For example, Extractors/SimpleLinearRegression/VotesExtractor.py

This may result in WET code, but will give us more flexibility when it comes down to customizing each extractor for different algorithms.  

@fikander what do you think?  @natron2244 ?

**Comment by chadfurman** [comment]
Things remaining:
1) finish SLR PostExtractor, use similar logic for users, votes, etc
2) write tests for SLR PostExtractor
3) write documentation for SLR PostExtractor
4) finish update to CLI to take in path to data file
5) update CLI to allow selection of SLR algorithm or "exit"

**Comment by chadfurman** [comment]
@fikander I started the post extractor using the Python3 built-in ElementTree

Admittedly, I just wrote a small bit of code and haven't yet tested it.  There could be syntax errors, logic errors, etc and definitely missing tests.  Just a bit of a start is all. 

I'll have to revisit this, or someone else can

**Comment by chadfurman** [comment]
Basic data extractor working for posts, good enough for now, closing this and moving on
